// This file is generated by Slice Machine. Update with care!

import Banner from './Banner';
import CallToActionSection from './CallToActionSection';
import Hero from './Hero';
import Introduction from './Introduction';
import ProductData from './ProductData';
import StorySection from './StorySection';
import TextParagraph from './TextParagraph';

export {
	Banner,
	CallToActionSection,
	Hero,
	Introduction,
	ProductData,
	StorySection,
	TextParagraph,
};

export const components = {
	banner: Banner,
	call_to_action_section: CallToActionSection,
	hero: Hero,
	introduction: Introduction,
	product_data: ProductData,
	story_section: StorySection,
	text_paragraph: TextParagraph,
};
