// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import ProductData from './ProductData';
import TextParagraph from './TextParagraph';

export {
	Hero,
	ProductData,
	TextParagraph,
};

export const components = {
	hero: Hero,
	product_data: ProductData,
	text_paragraph: TextParagraph,
};
