// This file is generated by Slice Machine. Update with care!

import ContentSection from './ContentSection';

export {
	ContentSection,
};

export const components = {
	content_section: ContentSection,
};
